version: '3.5'
services:
  front:
    container_name: front
    # image: lappis/smi-front:latest
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/smi-front
      - yarn_cache:/smi-front/node_modules
    networks:
      - smi-network
    environment:
      - MASTER_URL=http://0.0.0.0:8001

networks:
  smi-network:
    external: true

volumes:
  yarn_cache:
